// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7A8wcj4068OX7JDyf-N1ekXIsmn8gKCE',
    appId: '1:676306825199:web:23347145329f07d58e501a',
    messagingSenderId: '676306825199',
    projectId: 'ecomarket-4ef67',
    authDomain: 'ecomarket-4ef67.firebaseapp.com',
    storageBucket: 'ecomarket-4ef67.appspot.com',
    measurementId: 'G-E41FS0JDW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfu7rtwc3JG7pF49JOttAg0p80kZYKEGU',
    appId: '1:676306825199:android:4b64e0c8f68bf79b8e501a',
    messagingSenderId: '676306825199',
    projectId: 'ecomarket-4ef67',
    storageBucket: 'ecomarket-4ef67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2xPfmGvf8NUjzAs9T9KEDTFsnfl68lPQ',
    appId: '1:676306825199:ios:370d725307f9cba78e501a',
    messagingSenderId: '676306825199',
    projectId: 'ecomarket-4ef67',
    storageBucket: 'ecomarket-4ef67.appspot.com',
    iosClientId: '676306825199-arkoteam5sn7iqh22v1acs48i8ueh5e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2xPfmGvf8NUjzAs9T9KEDTFsnfl68lPQ',
    appId: '1:676306825199:ios:bb0590a9896d610e8e501a',
    messagingSenderId: '676306825199',
    projectId: 'ecomarket-4ef67',
    storageBucket: 'ecomarket-4ef67.appspot.com',
    iosClientId: '676306825199-79fg81lg6pr66h1t3gs3gfj26bf2vq1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoMarket.RunnerTests',
  );
}
